exp_name: AMP_algo_test
graph_size_values: 
# NOTE: to perform single experiments, simply comment the graph size values that are not needed
  # - 100 
  # - 150 
  # - 200
  # - 300
  # - 400
  # - 480 
  # - 600
  # - 800 
  # - 1000
  # - 1200 
  # - 1500
  # - 2000
  # - 3000
  # - 5000
  - 10000 # tested with batch_size = 20; clique_testing_levels = 50; test_iterations = 1
  
# type of correction to use (in graphs_generation.py):
# - p_increase (old correction): increasing the p value of the graph without the clique so that the average degree is matched between the two graphs
# - p_reduce (new correction): reducing the p value of the graph where the clique will be added
p_correction_type: p_reduce

testing_parameters:
  max_clique_size_proportion_test:
    - 0.4 # (100-150-200)
    - 0.3 # (300, 400, 480, 600)
    - 0.12 # (800, 1000/1200)
    - 0.1 # (1500, 2000)
    - 0.05 # (3000, 5000)
    - 0.013 # (10000)
  num_test: 20  # number of graphs in each test iteration
  clique_testing_levels: 50  # number of different clique sizes to test (will be the number of datapoints in the test set)
  test_iterations: 1  # set to 1 for N=3000, 5000, 10000