models:
  - model_name: MLP
    hyperparameters:
      learning_rate: 0.01
      batch_size: 32
      dropout: 0.2
      
  - model_name: CNN
    hyperparameters:
      learning_rate: 0.01
      batch_size: 64

graph_size: 100 