graph_size: 100
# type of correction to use (in graphs_generation.py):
# - p_increase (old correction): increasing the p value of the graph without the clique so that the average degree is matched between the two graphs
# - p_reduce (new correction): reducing the p value of the graph where the clique will be added
p_correction_type: p_reduce

models:

  # each instance of "models" will be trained and tested with the hyperparameters specified
  
  - model_name: MLP
    hyperparameters:
      # training cycles (TO BE INCREASED):
      num_epochs: 10
      num_training_steps: 40
      # training, validation and test set sizes (TO BE INCREASED):
      num_train: 16
      num_val: 16
      num_test: 16
      # other hyperparameters:
      learning_rate: 0.01
      dropout: 0.2
      # training structure:
      max_clique_size_proportion: 0.6
      min_clique_size_proportion: 0.4
      jump: 5
      save_step: 10