exp_name: VGG_experiment
graph_size: 300
# type of correction to use (in graphs_generation.py):
# - p_increase (old correction): increasing the p value of the graph without the clique so that the average degree is matched between the two graphs
# - p_reduce (new correction): reducing the p value of the graph where the clique will be added
p_correction_type: p_reduce

training_parameters:
  # training steps:
  num_training_steps: 500
  # training and validation set sizes:
  num_train: 32
  num_val: 32
  # other hyperparameters:
  learning_rate: 0.01  
  # training structure:
  max_clique_size_proportion: 0.6 # during training, clique will be at most 60% of the graph size
  min_clique_size_proportion: 0.4 # during training, clique will be at most 40% of the graph size
  clique_training_levels: 5
  save_step: 5
  # optimizer and loss function:
  optimizer: AdamW
  loss_function: BCELoss

testing_parameters:
  max_clique_size_proportion_test: 0.7 # during testing, clique will be at most 70% of the graph size
  num_test: 32  # number of graphs in each test iteration
  clique_testing_levels: 100  # number of different clique sizes to test (will be the number of datapoints in the test set)
  test_iterations: 16 # number of times for which a single clique size is tested      

models:

  - model_name: VGG16